{
	"version": 1645425530,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/sprite02-sheet0.png",
		"images/sprite03-sheet0.png",
		"images/sprite04-sheet0.png",
		"images/sprite05-sheet0.png",
		"images/sprite06-sheet0.png",
		"images/sprit07-sheet0.png",
		"images/sprite08-sheet0.png",
		"images/sprite09-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/spritejupiter-sheet0.png",
		"images/spritejupiter2-sheet0.png",
		"images/spritejupiter3-sheet0.png",
		"images/spritejupiter4-sheet0.png",
		"images/spritejupiter5-sheet0.png",
		"images/spritejupiter6-sheet0.png",
		"images/spritejupiter7-sheet0.png",
		"images/spritejupiter8-sheet0.png",
		"images/spritejupiter9-sheet0.png",
		"images/spritejupiter10-sheet0.png",
		"images/spritejupiter11-sheet0.png",
		"images/spritejupiter12-sheet0.png",
		"images/spritejupiter13-sheet0.png",
		"images/spritejupiter14-sheet0.png",
		"images/spritejupiter15-sheet0.png",
		"images/spritejupiter16-sheet0.png",
		"images/spritejupiter17-sheet0.png",
		"images/spritejupiter18-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"images/sprite3-sheet3.png",
		"images/sprite3-sheet4.png",
		"images/sprite3-sheet5.png",
		"images/sprite3-sheet6.png",
		"images/sprite3-sheet7.png",
		"images/sprite3-sheet8.png",
		"images/sprite3-sheet9.png",
		"images/sprite3-sheet10.png",
		"images/sprite3-sheet11.png",
		"images/sprite3-sheet12.png",
		"images/sprite3-sheet13.png",
		"images/sprite3-sheet14.png",
		"images/sprite3-sheet15.png",
		"images/sprite3-sheet16.png",
		"images/sprite3-sheet17.png",
		"images/sprite3-sheet18.png",
		"images/sprite3-sheet19.png",
		"images/sprite3-sheet20.png",
		"images/sprite3-sheet21.png",
		"images/sprite3-sheet22.png",
		"images/sprite3-sheet23.png",
		"images/sprite3-sheet24.png",
		"images/sprite3-sheet25.png",
		"images/sprite3-sheet26.png",
		"images/sprite3-sheet27.png",
		"images/sprite3-sheet28.png",
		"images/sprite3-sheet29.png",
		"images/sprite3-sheet30.png",
		"images/sprite3-sheet31.png",
		"images/sprite3-sheet32.png",
		"images/sprite3-sheet33.png",
		"images/sprite3-sheet34.png",
		"images/sprite3-sheet35.png",
		"images/sprite3-sheet36.png",
		"images/sprite3-sheet37.png",
		"images/sprite3-sheet38.png",
		"images/sprite3-sheet39.png",
		"images/sprite3-sheet40.png",
		"images/sprite3-sheet41.png",
		"images/sprite3-sheet42.png",
		"images/sprite3-sheet43.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/sprite4-sheet3.png",
		"images/sprite4-sheet4.png",
		"images/sprite4-sheet5.png",
		"images/sprite4-sheet6.png",
		"images/sprite4-sheet7.png",
		"images/sprite4-sheet8.png",
		"images/sprite4-sheet9.png",
		"images/sprite4-sheet10.png",
		"images/sprite4-sheet11.png",
		"images/sprite4-sheet12.png",
		"images/sprite4-sheet13.png",
		"images/sprite4-sheet14.png",
		"images/sprite4-sheet15.png",
		"images/sprite4-sheet16.png",
		"images/sprite4-sheet17.png",
		"images/sprite4-sheet18.png",
		"images/sprite4-sheet19.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite5-sheet2.png",
		"images/sprite5-sheet3.png",
		"images/sprite5-sheet4.png",
		"images/sprite5-sheet5.png",
		"images/sprite5-sheet6.png",
		"images/sprite5-sheet7.png",
		"images/sprite5-sheet8.png",
		"images/sprite5-sheet9.png",
		"images/sprite5-sheet10.png",
		"images/sprite5-sheet11.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/spriteneptune1-sheet0.png",
		"images/spriteneptune2-sheet0.png",
		"images/spritemercury-sheet0.png",
		"images/spritemercury-sheet1.png",
		"images/spritemercury-sheet2.png",
		"images/spritemercury-sheet3.png",
		"images/spritemercury-sheet4.png",
		"images/spritemercury-sheet5.png",
		"images/spritemercury-sheet6.png",
		"images/spritemercury-sheet7.png",
		"images/spritemercury-sheet8.png",
		"images/spritemercury-sheet9.png",
		"images/spritemercury-sheet10.png",
		"images/spritemercury-sheet11.png",
		"images/spritemercury-sheet12.png",
		"images/spritemercury-sheet13.png",
		"images/spritemercury-sheet14.png",
		"images/spritemercury-sheet15.png",
		"images/spritemercury-sheet16.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"asterism1.mp4",
		"celestial loop i1.mp4",
		"cosmogenesis1.mp4",
		"galactic imagination ii-1.mp4",
		"geometric storm-1.mp4",
		"holomorphic mandala-1.mp4",
		"lumeniferous-1.mp4",
		"musica universalis-1.mp4",
		"sevens-1.mp4",
		"soul mirror-1.mp4",
		"venus-1.mp4",
		"aurea1-1.mp4",
		"galactic synaptic-1.mp4",
		"sparks-1.mp4",
		"moonwave-1.mp4",
		"1-0001-1.mp4",
		"2-grsb1.mp4",
		"4-jupiter1.mp4",
		"3-jupiter-milky-way1.mp4",
		"5-peijove-20-1.mp4",
		"6-pj21-2-1.mp4",
		"7-sea of jupiter-1.mp4",
		"8-the spirit of jupiter1.mp4",
		"1-cosmograms-1.mp4",
		"2-spherical cosmograms-1.mp4",
		"3-cosmograms hd-1.mp4",
		"4-cosmogram-pyramid-2-1.mp4",
		"5-cosmogram ouroboros-1.mp4",
		"6-cosmogram aspects-1.mp4",
		"7-cosmograms - 64 universal symbols - philosophy-1.mp4",
		"8-codex0001-0720-1.mp4",
		"cassini-1.mp4",
		"cassini + vektroid - walk with me saturn-1.mp4",
		"zodiac 0-1.mp4",
		"zodiac 1-1.mp4",
		"moon.mp4"
	]
}